name: Trigger Sync Workflow
on:
  schedule:
    - cron: '0 * * * *' # Runs at the top of every hour
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  call-workflow:
    uses: crosnest/workflows/.github/workflows/chain-registry_sync.yml@main # Reference the reusable workflow
    with: # Pass inputs to the reusable workflow
      message: "Triggered from chain-registry"
