name: Sync Fork
on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch: {} # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for repository sync
    steps:
      - name: Sync Fork with Upstream
        run: gh repo sync $GITHUB_REPOSITORY -b $GITHUB_REF
